### ISSUE TITLE
超时是什么情况？

### ISSUE THREAD

**Issue by NeroLiang19** [Lcry/a-sheep-assistant#72]
【羊了个羊一键闯关开始启动】
...第1次开始完成闯关...
游戏服务器响应超时或崩溃中未及时响应，缓缓吧，等待服务器恢复后再试！本次程序运行结束，错误日志: HTTPSConnectionPool(host='cat-match.easygame2021.com', port=443): Max retries exceeded with url: /sheep/v1/game/game_over?rank_score=1&rank_state=1&rank_time=10&rank_role=1&skin=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002E9D922B370>, 'Connection to cat-match.easygame2021.com timed out. (connect timeout=6)'))
【羊了个羊一键闯关开始结束】

我在浏览器输入  https://cat-match.easygame2021.com 返回  ok 没问题

**Comment by LjyLab** [comment]
我刚刚试了一下也超时了

**Comment by lx2018new** [comment]
我也超时了

**Comment by lx2018new** [comment]
找到问题了，把科学上网关了就成功了

**Comment by Find-ing** [comment]
服务器有问题，代码是没事的

**Comment by Jayzongzer** [comment]
我是这个样子：
## 开始执行... 2022-09-16 16:45:18

【羊了个羊一键闯关开始启动】
...第1次开始完成闯关...
生成随机完成耗时:540 s
游戏服务器响应超时或崩溃中未及时响应，缓缓吧，等待服务器恢复后再试！本次程序运行结束，错误日志: HTTPSConnectionPool(host='cat-match.easygame2021.com', port=443): Max retries exceeded with url: /sheep/v1/game/game_over?rank_score=1&rank_state=1&rank_time=540&rank_role=1&skin=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f3218cf9520>, 'Connection to cat-match.easygame2021.com timed out. (connect timeout=6)'))
【羊了个羊一键闯关开始结束】

## 执行结束... 2022-09-16 16:45:25 耗时 7 秒

**Comment by NeroLiang19** [comment]
伙伴们，解决了，我是把   res = requests.get(finish_api % (state, rank_time), headers=request_header, timeout=6)  中 connect timeout=6 去掉。然后同时 ，记得记得吧爬虫工具退出，然后就可以了
