### ISSUE TITLE
羊了个羊

### ISSUE THREAD

**Issue by AcLeiyu** [Lcry/a-sheep-assistant#75]
你这代码保熟吗？

**Comment by zhaowei1994** [comment]
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='cat-match.easygame2021.com', port=443): Max retries exceeded with url: /sheep/v1/game/game_over?rank_score=1&rank_state=1&rank_time=910&rank_role=1&skin=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002868E460640>, 'Connection to cat-match.easygame2021.com timed out. (connect timeout=None)'))

**Comment by Lcry** [comment]
游戏服务器接口限流限制，请勿频繁操作
