### ISSUE TITLE
头像不是本人，羊了个羊服务器出问题了？

### ISSUE THREAD

**Issue by linweiwei123** [Lcry/a-sheep-assistant#76]

**Comment by tomorrow-yes** [comment]
我循环跑了300次了还没成功。。。

**Comment by linweiwei123** [comment]
> 我循环跑了300次了还没成功。。。

次数不能太多，跑一次看看

**Comment by zhaozekai456** [comment]
【羊了个羊一键闯关开始启动】
...第1次开始完成闯关...
生成随机完成耗时:435 s
游戏服务器响应超时或崩溃中未及时响应，缓缓吧，等待服务器恢复后再试！本次程序运行结束，错误日志: HTTPSConnectionPool(host='cat-match.easygame2021.com', port=443): Max retries exceeded with url: /sheep/v1/game/game_over?rank_score=1&rank_state=1&rank_time=435&rank_role=1&skin=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E0A1636C50>, 'Connection to cat-match.easygame2021.com timed out. (connect timeout=6)'))
【羊了个羊一键闯关开始结束】

**Comment by linweiwei123** [comment]
这样就是成功了，你可以去首页看我的名片了

**Comment by tomorrow-yes** [comment]
> > 我循环跑了300次了还没成功。。。
> 
> 次数不能太多，跑一次看看

刚刚去吃饭，回来一看跑了600次后居然成功了25次。。。。。。。。。。
