### ISSUE TITLE
早上8点还可以，现在不可以了

### ISSUE THREAD

**Issue by Clearzero22** [Lcry/a-sheep-assistant#91]

**Comment by Lcry** [comment]
亲测还可行
生成随机时间间隔，防止游戏服务器接口限流导致失败 : 3 s
恭喜你! 本次闯关羊群状态成功
游戏服务器响应超时或崩溃中未及时响应，缓缓吧，等待服务器恢复后再试！本次失败请忽略，错误日志: HTTPSConnectionPool(host='cat-match.easygame2021.com', port=443): Max retries exceeded with url: /sheep/v1/game/topic_game_over?rank_score=1&rank_state=1&rank_time=650&rank_role=2&skin=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000000001C0CA460>, 'Connection to cat-match.easygame2021.com timed out. (connect timeout=10)'))
已成功完成6次
...第13次尝试完成闯关...
生成随机时间间隔，防止游戏服务器接口限流导致失败 : 3 s
恭喜你! 本次闯关羊群状态成功
游戏服务器响应超时或崩溃中未及时响应，缓缓吧，等待服务器恢复后再试！本次失败请忽略，错误日志: HTTPSConnectionPool(host='cat-match.easygame2021.com', port=443): Max retries exceeded with url: /sheep/v1/game/topic_game_over?rank_score=1&rank_state=1&rank_time=650&rank_role=2&skin=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000000001C0C2550>, 'Connection to cat-match.easygame2021.com timed out. (connect timeout=10)'))
已成功完成7次
...第14次尝试完成闯关...
生成随机时间间隔，防止游戏服务器接口限流导致失败 : 5 s
恭喜你! 本次闯关羊群状态成功
恭喜你! 本次闯关话题状态成功
已成功完成9次
...第15次尝试完成闯关...
生成随机时间间隔，防止游戏服务器接口限流导致失败 : 6 s
